USER-SUPPLIED VALUES:
extraArgs:
- --clientRateLimitQPS=20
- --clientRateLimitBurst=50
initResources:
  limits:
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 40
readinessProbe:
  initialDelaySeconds: 35
  periodSeconds: 20
resources:
  limits:
    memory: 1024Mi
securityContext: null
