{
 "title": "Policy Framework Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Root Policies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(policy_governance_info{type=\"root\"} == 0)",
     "legendFormat": "Compliant Policies"
    },
    {
     "expr": "count(policy_governance_info{type=\"root\"} == 1)",
     "legendFormat": "NonCompliant Policies"
    }
   ]
  },
  {
   "title": "Propagated Policies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(policy_governance_info{type=\"propagated\"} == 0)",
     "legendFormat": "Compliant Propagated"
    },
    {
     "expr": "count(policy_governance_info{type=\"propagated\"} == 1)",
     "legendFormat": "NonCompliant Propagated"
    }
   ]
  },
  {
   "title": "Policy Propagator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"policy-propagator\"}[15m]))",
     "legendFormat": "Propagator Reconciles"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{controller=\"policy-propagator\"}[15m]))",
     "legendFormat": "Propagator Reconcile Errors"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"policy-set\"}[15m]))",
     "legendFormat": "PolicySet Reconciles"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{controller=\"policy-set\"}[15m]))",
     "legendFormat": "PolicySet Reconcile Errors"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"policy-encryption-keys\"}[15m]))",
     "legendFormat": "Encryption Key Reconciles"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{controller=\"policy-encryption-keys\"}[15m]))",
     "legendFormat": "Encryption Key Reconcile Errors"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"root-policy-status\"}[15m]))",
     "legendFormat": "Status Reconciles"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{controller=\"root-policy-status\"}[15m]))",
     "legendFormat": "Status Reconcile Errors"
    }
   ]
  },
  {
   "title": "Policy Sync Health",
   "type": "timeseries",
   "description": "View the work queue and the queue depth",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(workqueue_depth{name=\"policy-status-sync\"}[15m])",
     "legendFormat": "Work Queue Depth"
    },
    {
     "expr": "sum(delta(controller_runtime_reconcile_total{controller=\"policy-status-sync\"}[15m]))",
     "legendFormat": "Total Reconciles"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{controller=\"policy-status-sync\"}[15m]))",
     "legendFormat": "Failed Reconciles"
    }
   ]
  },
  {
   "title": "Policy Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster_namespace) (avg_over_time(policy_governance_info{type=\"propagated\"}[15m]))",
     "legendFormat": "Deployed NonCompliant"
    },
    {
     "expr": "count(policy_governance_info{type=\"propagated\"})",
     "legendFormat": "Propagated Policies"
    },
    {
     "expr": "count(policy_governance_info{type=\"root\"})",
     "legendFormat": "Root Policies"
    }
   ]
  },
  {
   "title": "Template Sync Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"policy-template-sync\"}[15m]))",
     "legendFormat": "Reconciles"
    },
    {
     "expr": "sum(increase(policy_system_errors_total{service=\"governance-policy-framework-metrics\"}[15m]))",
     "legendFormat": "System Errors"
    },
    {
     "expr": "avg_over_time(workqueue_depth{name=\"policy-template-sync\"}[15m])",
     "legendFormat": "Workqueue Depth"
    }
   ]
  },
  {
   "title": "Restarting Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"config-policy-controller\"}",
     "legendFormat": "Config Policy Controller Restarts"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"governance-policy-framework-addon\"}",
     "legendFormat": "Governance Framework Restarts"
    }
   ]
  },
  {
   "title": "Configuration Policy Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(policy_system_errors_total{service=\"config-policy-controller-metrics\"}[15m]))",
     "legendFormat": "System Errors"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"config-policy-controller\"}[15m]))",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(increase(config_policy_evaluation_total[180s]))",
     "legendFormat": "Evaluations"
    }
   ]
  }
 ]
}