apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-opp-example-app
placementBindingDefaults:
  name: binding-policy-example-app
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  orderPolicies: true
  placement:
    placementPath: placement.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
- name: policy-example-setup
  manifests:
    - path: setup-resources.yaml
- name: policy-example-setup-status
  manifests:
    - path: setup-status.yaml
  remediationAction: inform
- name: policy-build-example-httpd
  manifests:
    - path: build-httpd-example.yaml
- name: policy-example-httpd
  manifests:
    - path: httpd-example.yaml
