apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  labels:
    app: hardening
  name: hardening-chan
  namespace: policies
spec:
  pathname: https://github.com/stolostron/policy-collection.git
  type: GitHub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: policygenerator/policy-sets/stable/acm-hardening
  labels:
    app: hardening
  name: hardening-sub
  namespace: policies
spec:
  channel: policies/hardening-chan
  placement:
    local: true
