apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: terminating-configpolicies
spec:
  remediationAction: inform
  severity: low
  namespaceSelector:
    include:
      - "{{hub .ManagedClusterName hub}}"
  object-templates:
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        status:
          compliant: Terminating

