apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubi-nores
  name: ubi-nores-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ubi-nores
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubi-nores
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep 3600
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        imagePullPolicy: Always
        name: ubi-nores
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - MKNOD
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
