apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubi
  name: ubi-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ubi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubi
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - 'while :; do sleep 10; done'
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        imagePullPolicy: Always
        name: ubi
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - MKNOD
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
